### ISSUE TITLE
A question about string meaning

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#41]
Hi, @bizley !

Could you tell me please what [this line](https://github.com/bizley/yii2-podium/blob/a115b92c2e1ca03afc15949918b4e81f6f444c08/src/views/forum/post.php#L43) means?) I mean, what does it show exactly? I can't seem to understand :stuck_out_tongue_closed_eyes:

**Comment by bizley** [comment]
Sure.

The same partial view is used for saved posts - `<small>` holds there relative time of post creation (and update). Tooltip displayes the same date but full.

The line from your question is used in partial view for the future post (there is editor there).  
So instead of creation date there is "in a while" = "creation time will be known after saving the post" and tooltip says "as soon as you click Post Reply" = "date will be saved with the post, so click save button".

Just a small joke, not very funny I'm afraid :wink: Hope it's clear now.

PS. Nice new avatar :+1:

**Comment by ekaterina-git** [comment]
Oh, that's ok, it's crystal clear now :) Thanks.

> PS. Nice new avatar :+1: 

thanks) I got a bit tired of that elePHPant)
