### ISSUE TITLE
composer remove dependancy issue

### ISSUE THREAD

**Issue by vishuB** [bizley/yii2-podium#42]
i remove your extension using `composer remove bizley/podium`.

show below image
![screenshot- domain date time](https://cloud.githubusercontent.com/assets/13677102/19619244/fb01a530-987f-11e6-966b-e34723ef42a5.jpg)

`bizley/podium` remove successfully but it's dependant extension can not remove.

**Comment by bizley** [comment]
Which package hasn't been removed?
This is more of a composer issue than Podium. Good idea is to update your composer (just like the warning message says).

**Comment by vishuB** [comment]
in your `composer.json` all required packages can't remove

```
    "bizley/quill": "^2.0",
    "cebe/yii2-gravatar": "*",
    "kartik-v/yii2-widget-fileinput": "*",
    "kartik-v/yii2-sortable": "*",
    "kartik-v/yii2-widget-select2": "*",
    "kartik-v/yii2-widget-datepicker": "*",
    "zelenin/yii2-rss": "*",
    "zelenin/yii2-slug-behavior": "*",
    "himiklab/yii2-recaptcha-widget": "^1.0"
```

**Comment by bizley** [comment]
All of them? Have you updated composer itself? Are you using these packages outside of Podium as well?

Anyway - this has nothing to do with Podium, it's composer issue (most probably because of the old version you are using). If updating doesn't help please report this at https://github.com/composer/composer/issues (you can refere to this issue here).
